theme = "ayu_evolve"

[editor]
end-of-line-diagnostics = "hint"
true-color = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "info"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
